name: BeamDashboardX Python Application Release

on:
  workflow_dispatch:
    inputs:
      build_num:
        description: 'build number (unique for a given day)'
        required: true
        default: '1'
      draft_bool:
        description: 'set to "true" to create draft release only'
        required: true
        default: 'false'

env:
  RELEASE_NAME: ${{ github.event.repository.name }}-v

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
    
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make Expiration
      run: |
        python make_expiration.py

    - name: Build with PyInstaller
      run: |
        pyinstaller streamlit_runner.spec
        
    - name: Stage scripts
      run: |
        cp BeamDashboardX.cs "dist/BeamDashboardX.cs"
        cp beam_dashboard_x.py "dist/beam_dashboard_x.py"

    - name: Zip
      run: |
        Compress-Archive `
          -Path "dist/*" `
          -DestinationPath "${{ env.RELEASE_NAME }}${{ steps.date.outputs.date }}.${{ github.event.inputs.build_num }}.zip"
    
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: ${{ env.RELEASE_NAME }}${{ steps.date.outputs.date }}.${{ github.event.inputs.build_num }}
        tag_name: ${{ steps.date.outputs.date }}.${{ github.event.inputs.build_num }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: ${{ github.event.inputs.draft_bool == 'true' }}
        prerelease: false
        body: |
          This is the official release of **`${{ github.event.repository.name }}`** `v${{ steps.date.outputs.date }}.${{ github.event.inputs.build_num }}`.
          The .zip file contains a portable "compiled" python executable created with PyInstaller along with an ESAPI single file script launcher (.cs).
          For use on Eclipse versions 16 and up.
          This software is valid for 365 days post release.
        files: ${{ env.RELEASE_NAME }}${{ steps.date.outputs.date }}.${{ github.event.inputs.build_num }}.zip
